/*var pruebasunitarias = Array(
    Array('1','programa','nombre_programa','1','aa',false),
    Array('1','programa','nombre_programa','2','aaaaaaa',true),
    Array('1','programa','nombre_programa','3','aaaaaaa',false),
    Array('2','programa','nombre_programa','4','aa'.repeat(100),false),
    Array('2','programa','nombre_programa','5','aaaaaaa',true),
    Array('2','programa','nombre_programa','6','aa'.repeat(100),true),
    // Array('2','publicacion','nombre_programa','7','aa'.repeat(100),true),
);*/

var pruebasunitarias = Array(
    Array(0, 'programa', 'id_programa', 0, '12345678', false),
    Array(0, 'programa', 'id_programa', 1, '123456', true),
    Array(1, 'programa', 'id_programa', 2, ' ', false),
    Array(1, 'programa', 'id_programa', 3, '123456', true),
    Array(2, 'programa', 'id_programa', 4, 'ABCD12', false),
    Array(2, 'programa', 'id_programa', 5, '123456', true),
    Array(3, 'programa', 'id_programa', 4, 'ABCD12', false),
    Array(3, 'programa', 'id_programa', 5, '123456', true),
    Array(0, 'programa', 'nombre_programa', 6, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(0, 'programa', 'nombre_programa', 7, 'Programa', true),
    Array(1, 'programa', 'nombre_programa', 8, 'Test', false),
    Array(1, 'programa', 'nombre_programa', 9, 'Programa', true),
    Array(2, 'programa', 'nombre_programa', 10, 'Test123', false),
    Array(2, 'programa', 'nombre_programa', 11, 'Programa', true),
    Array(3, 'programa', 'nombre_programa', 12, 'Café', false),
    Array(3, 'programa', 'nombre_programa', 13, 'Programa', true),
    Array(4, 'programa', 'nombre_programa', 12, 'Café', false),
    Array(4, 'programa', 'nombre_programa', 13, 'Programa', true),
    Array(0, 'programa', 'acronimo_programa', 14, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', false),
    Array(0, 'programa', 'acronimo_programa', 15, 'ABC', true),
    Array(1, 'programa', 'acronimo_programa', 16, 'AB', false),
    Array(1, 'programa', 'acronimo_programa', 17, 'ABC', true),
    Array(2, 'programa', 'acronimo_programa', 18, 'AB123', false),
    Array(2, 'programa', 'acronimo_programa', 19, 'ABC', true),
    Array(3, 'programa', 'acronimo_programa', 20, 'A&B', false),
    Array(3, 'programa', 'acronimo_programa', 21, 'ABC', true),
    Array(4, 'programa', 'acronimo_programa', 20, 'A&B', false),
    Array(4, 'programa', 'acronimo_programa', 21, 'ABC', true),
    Array(0, 'programa', 'nombre_original_programa', 22, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(0, 'programa', 'nombre_original_programa', 23, 'Programa', true),
    Array(1, 'programa', 'nombre_original_programa', 24, 'Test', false),
    Array(1, 'programa', 'nombre_original_programa', 25, 'Programa', true),
    Array(2, 'programa', 'nombre_original_programa', 26, 'Test123', false),
    Array(2, 'programa', 'nombre_original_programa', 27, 'Programa', true),
    Array(3, 'programa', 'nombre_original_programa', 28, 'Café', false),
    Array(3, 'programa', 'nombre_original_programa', 29, 'Programa', true),
    Array(4, 'programa', 'nombre_original_programa', 28, 'Café', false),
    Array(4, 'programa', 'nombre_original_programa', 29, 'Programa', true),
    Array(0, 'programa', 'autor_programa', 30, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(0, 'programa', 'autor_programa', 31, 'Autor', true),
    Array(1, 'programa', 'autor_programa', 32, 'Test', false),
    Array(1, 'programa', 'autor_programa', 33, 'Autor', true),
    Array(2, 'programa', 'autor_programa', 34, 'Test123', false),
    Array(2, 'programa', 'autor_programa', 35, 'Autor', true),
    Array(3, 'programa', 'autor_programa', 36, 'A&B', false),
    Array(3, 'programa', 'autor_programa', 37, 'Autor', true),
    Array(4, 'programa', 'autor_programa', 36, 'A&B', false),
    Array(4, 'programa', 'autor_programa', 37, 'Autor', true),
    Array(0, 'programa', 'autor_original_programa', 38, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(0, 'programa', 'autor_original_programa', 39, 'Autor', true),
    Array(1, 'programa', 'autor_original_programa', 40, 'Test', false),
    Array(1, 'programa', 'autor_original_programa', 41, 'Autor', true),
    Array(2, 'programa', 'autor_original_programa', 42, 'Test123', false),
    Array(2, 'programa', 'autor_original_programa', 43, 'Autor', true),
    Array(3, 'programa', 'autor_original_programa', 44, 'A&B', false),
    Array(3, 'programa', 'autor_original_programa', 45, 'Autor', true),
    Array(4, 'programa', 'autor_original_programa', 44, 'A&B', false),
    Array(4, 'programa', 'autor_original_programa', 45, 'Autor', true),
    Array(0, 'programa', 'ano_programa', 46, '12345', false),
    Array(0, 'programa', 'ano_programa', 47, '2022', true),
    Array(1, 'programa', 'ano_programa', 48, 'abcd', false),
    Array(1, 'programa', 'ano_programa', 49, '2022', true),
    Array(2, 'programa', 'ano_programa', 50, '2025', false),
    Array(2, 'programa', 'ano_programa', 51, '2022', true),
    Array(3, 'programa', 'ano_programa', 50, '2025', false),
    Array(3, 'programa', 'ano_programa', 51, '2022', true),
    Array(0, 'programa', 'ano_original_programa', 52, '12345', false),
    Array(0, 'programa', 'ano_original_programa', 53, '2022', true),
    Array(1, 'programa', 'ano_original_programa', 54, 'abcd', false),
    Array(1, 'programa', 'ano_original_programa', 55, '2022', true),
    Array(2, 'programa', 'ano_original_programa', 56, '2025', false),
    Array(2, 'programa', 'ano_original_programa', 57, '2022', true),
    Array(3, 'programa', 'ano_original_programa', 56, '2025', false),
    Array(3, 'programa', 'ano_original_programa', 57, '2022', true),
    Array(0, 'programa', 'requisitos_programa', 58, 'aaaaaaa...(x300)', false),
    Array(0, 'programa', 'requisitos_programa', 59, 'Requisitos', true),
    Array(1, 'programa', 'requisitos_programa', 60, 'Test', false),
    Array(1, 'programa', 'requisitos_programa', 61, 'Requisitos', true),
    Array(2, 'programa', 'requisitos_programa', 62, 'Test@123', false),
    Array(2, 'programa', 'requisitos_programa', 63, 'Requisitos', true),
    Array(3, 'programa', 'requisitos_programa', 64, 'Test@123', false),
    Array(3, 'programa', 'requisitos_programa', 65, 'Requisitos', true),
    Array(4, 'programa', 'requisitos_programa', 64, 'Test@123', false),
    Array(4, 'programa', 'requisitos_programa', 65, 'Requisitos', true),
    Array(0, 'programa', 'poblacion_desde_programa', 66, '123', false),
    Array(0, 'programa', 'poblacion_desde_programa', 67, '10', true),
    Array(1, 'programa', 'poblacion_desde_programa', 68, ' ', false),
    Array(1, 'programa', 'poblacion_desde_programa', 69, '10', true),
    Array(2, 'programa', 'poblacion_desde_programa', 70, 'ABC', false),
    Array(2, 'programa', 'poblacion_desde_programa', 71, '10', true),
    Array(3, 'programa', 'poblacion_desde_programa', 70, 'ABC', false),
    Array(3, 'programa', 'poblacion_desde_programa', 71, '10', true),
    Array(0, 'programa', 'poblacion_hasta_programa', 72, '123', false),
    Array(0, 'programa', 'poblacion_hasta_programa', 73, '10', true),
    Array(1, 'programa', 'poblacion_hasta_programa', 74, ' ', false),
    Array(1, 'programa', 'poblacion_hasta_programa', 75, '10', true),
    Array(2, 'programa', 'poblacion_hasta_programa', 76, 'ABC', false),
    Array(2, 'programa', 'poblacion_hasta_programa', 77, '10', true),
    Array(3, 'programa', 'poblacion_hasta_programa', 76, 'ABC', false),
    Array(3, 'programa', 'poblacion_hasta_programa', 77, '10', true),
    Array(0, 'programa', 'unidad_poblacion', 78, 'DÍAS', false),
    Array(0, 'programa', 'unidad_poblacion', 79, 'MESES', true),
    Array(1, 'programa', 'unidad_poblacion', 78, 'DÍAS', false),
    Array(1, 'programa', 'unidad_poblacion', 79, 'MESES', true),
    Array(0, 'programa', 'tipo_programa', 80, 'EVALUACIÓN INTERVENCIÓN', false),
    Array(0, 'programa', 'tipo_programa', 81, 'EVALUACIÓN', true),
    Array(1, 'programa', 'tipo_programa', 80, 'EVALUACIÓN INTERVENCIÓN', false),
    Array(1, 'programa', 'tipo_programa', 81, 'EVALUACIÓN', true),
    Array(0, 'programa', 'tiempo_aplicacion_programa', 82, '12345', false),
    Array(0, 'programa', 'tiempo_aplicacion_programa', 83, '1000', true),
    Array(1, 'programa', 'tiempo_aplicacion_programa', 84, ' ', false),
    Array(1, 'programa', 'tiempo_aplicacion_programa', 85, '1000', true),
    Array(2, 'programa', 'tiempo_aplicacion_programa', 86, 'ABCD', false),
    Array(2, 'programa', 'tiempo_aplicacion_programa', 87, '1000', true),
    Array(3, 'programa', 'tiempo_aplicacion_programa', 86, 'ABCD', false),
    Array(3, 'programa', 'tiempo_aplicacion_programa', 87, '1000', true),
    Array(0, 'programa', 'descrip_interp_programa', 88, 'aaaaaaa...(x5000)', false),
    Array(0, 'programa', 'descrip_interp_programa', 89, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(1, 'programa', 'descrip_interp_programa', 90, 'Breve descripción', false),
    Array(1, 'programa', 'descrip_interp_programa', 91, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(2, 'programa', 'descrip_interp_programa', 92, '123Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', false),
    Array(2, 'programa', 'descrip_interp_programa', 93, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(3, 'programa', 'descrip_interp_programa', 94, '@Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', false),
    Array(3, 'programa', 'descrip_interp_programa', 95, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(4, 'programa', 'descrip_interp_programa', 94, '@Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', false),
    Array(4, 'programa', 'descrip_interp_programa', 95, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(0, 'programa', 'fichero_programa', 96, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(0, 'programa', 'fichero_programa', 97, 'archivo.txt', true),
    Array(1, 'programa', 'fichero_programa', 98, 'archivo', false),
    Array(1, 'programa', 'fichero_programa', 99, 'archivo.txt', true),
    Array(2, 'programa', 'fichero_programa', 100, 'archivo123', false),
    Array(2, 'programa', 'fichero_programa', 101, 'archivo.txt', true),
    Array(3, 'programa', 'fichero_programa', 102, 'archivo@.txt', false),
    Array(3, 'programa', 'fichero_programa', 103, 'archivo.txt', true),
    Array(4, 'programa', 'fichero_programa', 102, 'archivo@.txt', false),
    Array(4, 'programa', 'fichero_programa', 103, 'archivo.txt', true),
    Array(0, 'programa', 'enlace_programa', 104, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(0, 'programa', 'enlace_programa', 105, 'http://www.ejemplo.com/archivo.html', true),
    Array(1, 'programa', 'enlace_programa', 106, 'http://.com', false),
    Array(1, 'programa', 'enlace_programa', 107, 'http://www.ejemplo.com/archivo.html', true),
    Array(2, 'programa', 'enlace_programa', 108, 'http://www.ejemplo123.com', false),
    Array(2, 'programa', 'enlace_programa', 109, 'http://www.ejemplo.com/archivo.html', true),
    Array(3, 'programa', 'enlace_programa', 110, 'http://www.ejemplo.com/archivo@.html', false),
    Array(3, 'programa', 'enlace_programa', 111, 'http://www.ejemplo.com/archivo.html', true),
    Array(4, 'programa', 'enlace_programa', 110, 'http://www.ejemplo.com/archivo@.html', false),
    Array(4, 'programa', 'enlace_programa', 111, 'http://www.ejemplo.com/archivo.html', true),
    Array(0, 'programa', 'formato_programa', 112, 'DIGITAL', false),
    Array(0, 'programa', 'formato_programa', 113, 'ELECTRÓNICO', true),
    Array(1, 'programa', 'formato_programa', 112, 'DIGITAL', false),
    Array(1, 'programa', 'formato_programa', 113, 'ELECTRÓNICO', true),
    Array(0, 'programa', 'modo_correccion_programa', 114, 'AUTOMÁTICO', false),
    Array(0, 'programa', 'modo_correccion_programa', 115, 'ELECTRÓNICO', true),
    Array(1, 'programa', 'modo_correccion_programa', 114, 'AUTOMÁTICO', false),
    Array(1, 'programa', 'modo_correccion_programa', 115, 'ELECTRÓNICO', true),
    Array(0, 'programa', 'modo_aplicacion_programa', 116, 'COLECTIVA', false),
    Array(0, 'programa', 'modo_aplicacion_programa', 117, 'INDIVIDUAL', true),
    Array(1, 'programa', 'modo_aplicacion_programa', 116, 'COLECTIVA', false),
    Array(1, 'programa', 'modo_aplicacion_programa', 117, 'INDIVIDUAL', true),
    Array(0, 'programa', 'imagen_programa', 118, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(0, 'programa', 'imagen_programa', 119, 'imagen.jpg', true),
    Array(1, 'programa', 'imagen_programa', 120, 'imagen', false),
    Array(1, 'programa', 'imagen_programa', 121, 'imagen.jpg', true),
    Array(2, 'programa', 'imagen_programa', 122, 'imagen123', false),
    Array(2, 'programa', 'imagen_programa', 123, 'imagen.jpg', true),
    Array(3, 'programa', 'imagen_programa', 124, 'imagen@.jpg', false),
    Array(3, 'programa', 'imagen_programa', 125, 'imagen.jpg', true),
    Array(4, 'programa', 'imagen_programa', 124, 'imagen@.jpg', false),
    Array(4, 'programa', 'imagen_programa', 125, 'imagen.jpg', true)
);

