var def_test = Array(
    Array('programa', 'id_programa', 0, 'Tamaño mayor a 6', false, 'El id_programa no puede tener más de 6 caracteres'),
    Array('programa', 'id_programa', 1, 'Tamaño menor a 1', false, 'El id_programa no puede tener menos de 1 caracter'),
    Array('programa', 'id_programa', 2, 'Contenido diferente a dígitos', false, 'El id_programa solo puede contener dígitos numéricos'),
    Array('programa', 'id_programa', 3, 'Dígitos min 1 max 6', true, 'Éxito'),
    Array('programa', 'nombre_programa', 4, 'Tamaño mayor a 60', false, 'El nombre_programa no puede tener más de 60 caracteres'),
    Array('programa', 'nombre_programa', 5, 'Tamaño menor a 6', false, 'El nombre_programa no puede tener menos de 6 caracteres'),
    Array('programa', 'nombre_programa', 6, 'Contenido con dígitos', false, 'El nombre_programa no puede contener dígitos numéricos'),
    Array('programa', 'nombre_programa', 7, 'Caracteres especiales', false, 'El nombre_programa solo acepta alfabéticos con acento, ñ y espacios'),
    Array('programa', 'nombre_programa', 8, 'Alfabéticos con acentos, ñ y espacios min 6 max 60', true, 'Éxito'),
    Array('programa', 'acronimo_programa', 9, 'Tamaño mayor a 20', false, 'El acronimo_programa no puede tener más de 20 caracteres'),
    Array('programa', 'acronimo_programa', 10, 'Tamaño menor a 3', false, 'El acronimo_programa no puede tener menos de 3 caracteres'),
    Array('programa', 'acronimo_programa', 11, 'Contenido con dígitos', false, 'El acronimo_programa no puede contener dígitos numéricos'),
    Array('programa', 'acronimo_programa', 12, 'Caracteres especiales', false, 'El acronimo_programa no acepta caracteres especiales ni alfabéticos con acento y con espacios'),
    Array('programa', 'acronimo_programa', 13, 'Alfabéticos sin acentos ni espacios min 3 max 20', true, 'Éxito'),
    Array('programa', 'nombre_original_programa', 14, 'Tamaño mayor a 60', false, 'El nombre_original_programa no puede tener más de 60 caracteres'),
    Array('programa', 'nombre_original_programa', 15, 'Tamaño menor a 6', false, 'El nombre_programa no puede tener menos de 6 caracteres'),
    Array('programa', 'nombre_original_programa', 16, 'Contenido con dígitos', false, 'El nombre_programa no puede contener dígitos numéricos'),
    Array('programa', 'nombre_original_programa', 17, 'Caracteres especiales', false, 'El nombre_programa solo acepta alfabéticos con acento, ñ y espacios'),
    Array('programa', 'nombre_original_programa', 18, 'Alfabéticos con acentos, ñ y espacios min 6 max 60', true, 'Éxito'),
    Array('programa', 'autor_programa', 19, ' Tamaño mayor a 50', false, ' El autor_programa no puede tener más de 50 caracteres'),
    Array('programa', 'autor_programa', 20, ' Tamaño menor a 6', false, ' El autor_programa no puede tener menos de 6 caracteres'),
    Array('programa', 'autor_programa', 21, 'Contenido con dígitos', false, ' El autor_programa no puede tener dígitos  numericos'),
    Array('programa', 'autor_programa', 22, ' Caracteres especiales', false, ' El autor_programa solo acepta alfabéticos con acento  ñ y espacios'),
    Array('programa', 'autor_programa', 23, 'Alfabéticos con acentos, ñ y espacios min 6 max 50', true, 'Éxito'),
    Array('programa', 'autor_original_programa', 24, ' Tamaño mayor a 50', false, ' El autor_original_programa no puede tener más de 50 caracteres'),
    Array('programa', 'autor_original_programa', 25, ' Tamaño menor a 6', false, ' El autor_original_programa no puede tener menos de 6 caracteres'),
    Array('programa', 'autor_original_programa', 26, 'Contenido con dígitos', false, ' El autor_original_programa no puede tener dígitos numericos'),
    Array('programa', 'autor_original_programa', 27, ' Caracteres especiales', false, ' El autor_original_programa solo acepta alfabéticos con acento  ñ y espacios'),
    Array('programa', 'autor_original_programa', 28, ' Alfabéticos con acentos, ñ y espacios min 6 max 50', true, 'Éxito'),
    Array('programa', 'ano_programa', 29, ' Tamaño distinto de 4', false, ' El año del programa debe tener 4 dígitos'),
    Array('programa', 'ano_programa', 30, ' Contenido diferente a dígitos', false, ' El año del programa solo puede contener dígitos numéricos'),
    Array('programa', 'ano_programa', 31, ' Año superior al actual', false, ' El año del programa no puede ser superior al año actual'),
    Array('programa', 'ano_programa', 32, ' Dígitos 4 min 4 max, año no superior actual', true, 'Éxito'),
    Array('programa', 'ano_original_programa', 33, ' Tamaño distinto de 4', false, ' El año original del programa debe tener 4 dígitos'),
    Array('programa', 'ano_original_programa', 34, ' Contenido diferente a dígitos', false, ' El año original del programa solo puede contener dígitos numéricos'),
    Array('programa', 'ano_original_programa', 35, ' Año superior al actual', false, ' El año original del programa no puede ser superior al año actual'),
    Array('programa', 'ano_original_programa', 36, ' Dígitos 4 min 4 max, año no superior actual', true, 'Éxito'),
    Array('programa', 'requisitos_programa', 37, ' Tamaño mayor a 300', false, ' Los requisitos del programa no pueden tener más de 300 caracteres'),
    Array('programa', 'requisitos_programa', 38, ' Tamaño menor a 6', false, ' Los requisitos del programa no pueden tener menos de 6 caracteres'),
    Array('programa', 'requisitos_programa', 39, 'Contenido con dígitos', false, ' Los requisitos del programa no puede tener dígitos numericos'),
    Array('programa', 'requisitos_programa', 40, ' Caracteres no permitidos', false, ' Los requisitos del programa solo aceptan alfabéticos con acento ñ  espacios y signos de puntuación'),
    Array('programa', 'requisitos_programa', 41, ' Alfabéticos con acentos, ñ, espacios y signos de puntuación min 6 max 300', true, 'Éxito'),
    Array('programa', 'poblacion_desde_programa', 42, ' Tamaño mayor a 2', false, ' La población desde del programa no puede tener más de 2 dígitos'),
    Array('programa', 'poblacion_desde_programa', 43, ' Tamaño menor a 1', false, ' La población desde del programa no puede tener menos de 1 dígito'),
    Array('programa', 'poblacion_desde_programa', 44, ' Contenido diferente a dígitos', false, ' La población desde del programa solo puede contener dígitos numéricos'),
    Array('programa', 'poblacion_desde_programa', 45, ' Dígitos min 1 max 2', true, 'Éxito'),
    Array('programa', 'poblacion_hasta_programa', 46, ' Tamaño mayor a 2', false, ' La población hasta del programa no puede tener más de 2 dígitos'),
    Array('programa', 'poblacion_hasta_programa', 47, ' Tamaño menor a 1', false, ' La población hasta del programa no puede tener menos de 1 dígito'),
    Array('programa', 'poblacion_hasta_programa', 48, ' Contenido diferente a dígitos', false, ' La población hasta del programa solo puede contener dígitos numéricos'),
    Array('programa', 'poblacion_hasta_programa', 49, ' Dígitos min 1 max 2', true, 'Éxito'),
    Array('programa', 'unidad_poblacion', 50, ' Valor no permitido', false, ' La unidad de población solo puede ser "MESES" o "AÑOS"'),
    Array('programa', 'unidad_poblacion', 51, ' Solo valores (\'MESES\',\'AÑOS\')', false, 'Éxito'),
    Array('programa', 'tipo_programa', 52, ' Valor no permitido', false, ' El tipo de programa solo puede ser "EVALUACIÓN"  "INTERVENCIÓN" o "EVALUACIÓN E INTERVENCIÓN"'),
    Array('programa', 'tipo_programa', 53, ' Solo valores \'EVALUACIÓN\' , \'INTERVENCIÓN\' , \'EVALUACIÓN E INTERVENCIÓN\'', true, 'Éxito'),
    Array('programa', 'tiempo_aplicacion_programa', 54, ' Tamaño mayor a 4', false, ' El tiempo de aplicación del programa no puede tener más de 4 dígitos'),
    Array('programa', 'tiempo_aplicacion_programa', 55, ' Tamaño menor a 1', false, ' El tiempo de aplicación del programa no puede tener menos de 1 dígito'),
    Array('programa', 'tiempo_aplicacion_programa', 56, ' Contenido diferente a dígitos', false, ' El tiempo de aplicación del programa solo puede contener dígitos numéricos'),
    Array('programa', 'tiempo_aplicacion_programa', 57, ' Dígitos min 1 max 4', true, 'Éxito'),
    Array('programa', 'descrip_interp_programa', 58, ' Tamaño mayor a 5000', false, ' La descripción e interpretación del programa no puede tener más de 5000 caracteres'),
    Array('programa', 'descrip_interp_programa', 59, ' Tamaño menor a 100', false, ' La descripción e interpretación del programa no puede tener menos de 100 caracteres'),
    Array('programa', 'descrip_interp_programa', 60, 'Contenido con dígitos', false, ' La descripción e interpretación del programa no puede tener dígitos numericos'),
    Array('programa', 'descrip_interp_programa', 61, ' Caracteres no permitidos', false, ' La descripción e interpretación del programa solo acepta alfabéticos con acento ñ espacios  signos de puntuación y retornos de carro'),
    Array('programa', 'descrip_interp_programa', 62, ' Alfabéticos con acentos, ñ, espacios, signos de puntuación y retornos de carro min 100 max 5000', true, 'Éxito'),
    Array('programa', 'fichero_programa', 63, ' Tamaño mayor a 60', false, ' El nombre del fichero del programa no puede tener más de 60 caracteres'),
    Array('programa', 'fichero_programa', 64, ' Tamaño menor a 7', false, ' El nombre del fichero del programa no puede tener menos de 7 caracteres'),
    Array('programa', 'fichero_programa', 65, 'Contenido con dígitos', false, ' El nombre del fichero del programa no puede tener dígitos numericos'),
    Array('programa', 'fichero_programa', 66, ' Caracteres no permitidos', false, ' El nombre del fichero del programa solo acepta alfabéticos sin acento  sin ñ y sin espacios'),
    Array('programa', 'fichero_programa', 67, ' Alfabéticos sin acentos ni ñ ni espacios min 7 max 60', true, 'Éxito'),
    Array('programa', 'enlace_programa', 68, ' Tamaño mayor a 100', false, ' El enlace del programa no puede tener más de 100 caracteres'),
    Array('programa', 'enlace_programa', 69, ' Tamaño menor a 10', false, ' El enlace del programa no puede tener menos de 10 caracteres'),
    Array('programa', 'enlace_programa', 69, ' Tamaño menor a 10', false, ' El enlace del programa no puede tener menos de 10 caracteres'),
    Array('programa', 'enlace_programa', 70, ' Tamaño mayor a 100', false, ' El enlace del programa no puede tener más de 100 caracteres'),
    Array('programa', 'enlace_programa', 71, ' Tamaño menor a 10', false, ' El enlace del programa no puede tener menos de 10 caracteres'),
    Array('programa', 'enlace_programa', 72, ' Contenido con dígitos', false, ' El enlace del programa no puede tener dígitos numéricos'),
    Array('programa', 'enlace_programa', 73, ' Caracteres no permitidos', false, ' El enlace del programa solo acepta alfabéticos ":"  "/" y "." sin acentos  ñ ni espacios'),
    Array('programa', 'enlace_programa', 74, ' alfabéticos y : y / y . sin acentos ni ñ ni espacios min 10 max 100', true, ' Éxito'),
    Array('programa', 'formato_programa', 75, ' Valor no permitido', false, ' El formato del programa solo puede ser "PAPEL"  "ELECTRÓNICO" o "PAPEL Y ELECTRÓNICO"'),
    Array('programa', 'formato_programa', 76, ' solo valores (\'PAPEL\', \'ELECTRÓNICO\',\'PAPEL Y ELECTRÓNICO\')', true, ' Éxito'),
    Array('programa', 'modo_correccion_programa', 77, ' Valor no permitido', false, ' El modo de corrección del programa solo puede ser "PAPEL"  "ELECTRÓNICO" o "PAPEL Y ELECTRÓNICO"'),
    Array('programa', 'modo_correccion_programa', 78, ' solo valores (\'PAPEL\', \'ELECTRÓNICO\',\'PAPEL Y ELECTRÓNICO\')', true, ' Éxito'),
    Array('programa', 'modo_aplicacion_programa', 79, ' Valor no permitido', false, ' El modo de aplicación del programa solo puede ser "INDIVIDUAL"  "COLECTIVO" o "INDIVIDUAL Y COLECTIVO"'),
    Array('programa', 'modo_aplicacion_programa', 80, ' solo valores \'INDIVIDUAL\',\'COLECTIVO\',\'INDIVIDUAL Y COLECTIVO\'', true, ' Éxito'),
    Array('programa', 'tiempo_aplicacion_programa', 81, ' Tamaño mayor a 4', false, ' El tiempo de aplicación del programa no puede tener más de 4 dígitos'),
    Array('programa', 'tiempo_aplicacion_programa', 82, ' Tamaño menor a 1', false, ' El tiempo de aplicación del programa no puede tener menos de 1 dígito'),
    Array('programa', 'tiempo_aplicacion_programa', 83, ' Contenido diferente a dígitos', false, ' El tiempo de aplicación del programa solo puede contener dígitos numéricos'),
    Array('programa', 'tiempo_aplicacion_programa', 84, ' dígitos min 1 max 4', true, ' Éxito'),
    Array('programa', 'descrip_interp_programa', 85, ' Tamaño mayor a 5000', false, ' La descripción e interpretación del programa no puede tener más de 5000 caracteres'),
    Array('programa', 'descrip_interp_programa', 86, ' Tamaño menor a 100', false, ' La descripción e interpretación del programa no puede tener menos de 100 caracteres'),
    Array('programa', 'descrip_interp_programa', 87, ' Contenido con dígitos', false, ' La descripción e interpretación del programa no puede tener dígitos numéricos'),
    Array('programa', 'descrip_interp_programa', 88, ' Caracteres no permitidos', false, ' La descripción e interpretación del programa solo acepta alfabéticos con acento ñ espacios  signos de puntuación y retornos de carro'),
    Array('programa', 'descrip_interp_programa', 89, ' Alfabéticos con acentos, ñ, espacios, signos de puntuación y retornos de carro min 100 max 5000', true, ' Éxito'),
    Array('programa', 'fichero_programa', 90, ' Tamaño mayor a 60', false, ' El nombre del fichero del programa no puede tener más de 60 caracteres'),
    Array('programa', 'fichero_programa', 91, ' Tamaño menor a 7', false, ' El nombre del fichero del programa no puede tener menos de 7 caracteres'),
    Array('programa', 'fichero_programa', 92, ' Contenido con dígitos', false, ' El nombre del fichero del programa no puede tener dígitos numéricos'),
    Array('programa', 'fichero_programa', 93, ' Caracteres no permitidos', false, ' El nombre del fichero del programa solo acepta alfabéticos sin acento  sin ñ y sin espacios'),
    Array('programa', 'fichero_programa', 94, ' Alfabéticos sin acentos ni ñ ni espacios min 7 max 60', true, ' Éxito'),
    Array('programa', 'imagen_programa', 95, ' Tamaño mayor a 60', false, ' El nombre de la imagen del programa no puede tener más de 60 caracteres'),
    Array('programa', 'imagen_programa', 96, ' Tamaño menor a 7', false, ' El nombre de la imagen del programa no puede tener menos de 7 caracteres'),
    Array('programa', 'imagen_programa', 97, ' Contenido con dígitos', false, ' El nombre de la imagen del programa no puede tener dígitos numéricos'),
    Array('programa', 'imagen_programa', 98, ' Caracteres no permitidos', false, ' El nombre de la imagen del programa solo acepta alfabéticos sin acento  sin ñ y sin espacios'),
    Array('programa', 'imagen_programa', 99, ' Alfabéticos sin acentos ni ñ ni espacios min 7 max 60', true, ' Éxito'),
    
    Array('publicacion','id_publicacion',100,'Tamaño mayor a 6',false,'El id_publicacion no puede tener más de 6 caracteres'),
    Array('publicacion','id_publicacion',101,'Tamaño menor a 1',false,'El id_publicacion no puede tener menos de 1 caracter'),
    Array('publicacion','id_publicacion',102,'Contenido diferente a dígitos',false,'El id_publicacion solo puede contener dígitos numéricos'),
    Array('publicacion','id_publicacion',103,'Dígitos min 1 max 6',true,'Éxito'),
    Array('publicacion','titulo_publicacion',104,'Tamaño mayor a 80',false,'El titulo_publicacion no puede tener más de 80 caracteres'),
    Array('publicacion','titulo_publicacion',105,'Tamaño menor a 6',false,'El titulo_publicacion no puede tener menos de 6 caracteres'),
    Array('publicacion','titulo_publicacion',106,'Contenido con dígitos',false,'El titulo_publicacion no puede contener dígitos numéricos'),
    Array('publicacion','titulo_publicacion',107,'Caracteres especiales',false,'El titulo_publicacion solo acepta alfabéticos con acento, ñ y espacios'),
    Array('publicacion','titulo_publicacion',108,'Alfabéticos con acentos, ñ y espacios min 6 max 80',true,'Éxito'),
    Array('publicacion','autor_publicacion',109,'Tamaño mayor a 40',false,'El autor_publicacion no puede tener más de 40 caracteres'),
    Array('publicacion','autor_publicacion',110,'Tamaño menor a 6',false,'El autor_publicacion no puede tener menos de 6 caracteres'),
    Array('publicacion','autor_publicacion',111,'Contenido con dígitos',false,'El autor_publicacion no puede contener dígitos numéricos'),
    Array('publicacion','autor_publicacion',112,'Caracteres especiales',false,'El autor_publicacion solo acepta alfabéticos con acento, ñ y espacios'),
    Array('publicacion','autor_publicacion',113,'Alfabéticos con acentos, ñ y espacios min 6 max 40',true,'Éxito'),
    Array('publicacion','fecha_publicacion',114,'Fecha inválida',false,'La fecha_publicacion debe ser una fecha válida con formato dd/mm/aaaa'),
    Array('publicacion','fecha_publicacion',115,'Fecha válida presente o futura con formato dd/mm/aaaa',true,'Éxito'),
    Array('publicacion','area_publicacion',116,'Tamaño mayor a 6',false,'El area_publicacion no puede tener más de 6 caracteres'),
    Array('publicacion','area_publicacion',117,'Tamaño menor a 1',false,'El area_publicacion no puede tener menos de 1 caracter'),
    Array('publicacion','area_publicacion',118,'Contenido diferente a dígitos',false,'El area_publicacion solo puede contener dígitos numéricos'),
    Array('publicacion','area_publicacion',119,'Dígitos min 1 max 6',true,'Éxito'),
    Array('publicacion','texto_publicacion',120,'Tamaño mayor a 8000',false,'El texto_publicacion no puede tener más de 8000 caracteres'),
    Array('publicacion','texto_publicacion',121,'Tamaño menor a 30',false,'El texto_publicacion no puede tener menos de 30 caracteres'),
    Array('publicacion','texto_publicacion',122,'Cualquier ascii min 30 max 8000',true,'Éxito'),
    Array('publicacion','imagen_publicacion',123,'Tamaño mayor a 50',false,'La imagen_publicacion no puede tener más de 50 caracteres'),
    Array('publicacion','imagen_publicacion',124,'Tamaño menor a 7',false,'La imagen_publicacion no puede tener menos de 7 caracteres'),
    Array('publicacion','imagen_publicacion',125,'Contenido con acentos, ñ o espacios',false,'La imagen_publicacion solo puede contener alfabéticos sin acentos ni ñ ni espacios'),
    Array('publicacion','imagen_publicacion',126,'Formato no válido',false,'La imagen_publicacion debe ser en formato jpg o jpeg'),
    Array('publicacion','imagen_publicacion',127,'Alfabéticos sin acentos ni ñ ni espacios min 7 max 50. Solo jpg o jpeg y tamaño de fichero menor de 20000 bytes',true,'Éxito'),
    
    );
    
  



