var pruebasunitarias =  
Array(
    Array(0, 'programa', 'id_programa', 0, '12345678', false),
    Array(0, 'programa', 'id_programa', 1, '123456', true),
    Array(1, 'programa', 'id_programa', 2, ' ', false),
    Array(1, 'programa', 'id_programa', 3, '123456', true),
    Array(2, 'programa', 'id_programa', 4, 'ABCD12', false),
    Array(2, 'programa', 'id_programa', 5, '123456', true),
    Array(3, 'programa', 'id_programa', 6, 'ABCD12', false),
    Array(3, 'programa', 'id_programa', 7, '123456', true),
    Array(4, 'programa', 'nombre_programa', 8, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(4, 'programa', 'nombre_programa', 9, 'Programa', true),
    Array(5, 'programa', 'nombre_programa', 10, 'Test', false),
    Array(5, 'programa', 'nombre_programa', 11, 'Programa', true),
    Array(6, 'programa', 'nombre_programa', 12, 'Test123', false),
    Array(6, 'programa', 'nombre_programa', 13, 'Programa', true),
    Array(7, 'programa', 'nombre_programa', 14, 'Café', false),
    Array(7, 'programa', 'nombre_programa', 15, 'Programa', true),
    Array(8, 'programa', 'acronimo_programa', 16, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', false),
    Array(8, 'programa', 'acronimo_programa', 17, 'ABC', true),
    Array(9, 'programa', 'acronimo_programa', 18, 'AB', false),
    Array(9, 'programa', 'acronimo_programa', 19, 'ABC', true),
    Array(10, 'programa', 'acronimo_programa', 20, 'AB123', false),
    Array(10, 'programa', 'acronimo_programa', 21, 'ABC', true),
    Array(11, 'programa', 'acronimo_programa', 22, 'A&B', false),
    Array(11, 'programa', 'acronimo_programa', 23, 'ABC', true),
    Array(12, 'programa', 'acronimo_programa', 24, 'A&B', false),
    Array(12, 'programa', 'acronimo_programa', 25, 'ABC', true),
    Array(13, 'programa', 'nombre_original_programa', 26, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(13, 'programa', 'nombre_original_programa', 27, 'Programa', true),
    Array(14, 'programa', 'nombre_original_programa', 28, 'Test', false),
    Array(14, 'programa', 'nombre_original_programa', 29, 'Programa', true),
    Array(15, 'programa', 'nombre_original_programa', 30, 'Test123', false),
    Array(15, 'programa', 'nombre_original_programa', 31, 'Programa', true),
    Array(16, 'programa', 'nombre_original_programa', 32, 'Café', false),
    Array(16, 'programa', 'nombre_original_programa', 33, 'Programa', true),
    Array(17, 'programa', 'nombre_original_programa', 34, 'Café', false),
    Array(17, 'programa', 'nombre_original_programa', 35, 'Programa', true),
    Array(18, 'programa', 'autor_programa', 36, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(18, 'programa', 'autor_programa', 37, 'Autora', true),
    Array(19, 'programa', 'autor_programa', 38, 'Test', false),
    Array(19, 'programa', 'autor_programa', 39, 'Autora', true),
    Array(20, 'programa', 'autor_programa', 40, 'Test123', false),
    Array(20, 'programa', 'autor_programa', 41, 'Autora', true),
    Array(21, 'programa', 'autor_programa', 42, 'A&B', false),
    Array(21, 'programa', 'autor_programa', 43, 'Autora', true),
    Array(22, 'programa', 'autor_programa', 44, 'A&B', false),
    Array(22, 'programa', 'autor_programa', 45, 'Autora', true),
    Array(23, 'programa', 'autor_original_programa', 46, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(23, 'programa', 'autor_original_programa', 47, 'Autora', true),
    Array(24, 'programa', 'autor_original_programa', 48, 'Test', false),
    Array(24, 'programa', 'autor_original_programa', 49, 'Autora', true),
    Array(25, 'programa', 'autor_original_programa', 50, 'Test123', false),
    Array(25, 'programa', 'autor_original_programa', 51, 'Autora', true),
    Array(26, 'programa', 'autor_original_programa', 52, 'A&B', false),
    Array(26, 'programa', 'autor_original_programa', 53, 'Autora', true),
    Array(27, 'programa', 'autor_original_programa', 54, 'A&B', false),
    Array(27, 'programa', 'autor_original_programa', 55, 'Autora', true),
    Array(28, 'programa', 'ano_programa', 56, '12345', false),
    Array(28, 'programa', 'ano_programa', 57, '2022', true),
    Array(29, 'programa', 'ano_programa', 58, 'abcd', false),
    Array(29, 'programa', 'ano_programa', 59, '2022', true),
    Array(30, 'programa', 'ano_programa', 60, '2025', false),
    Array(30, 'programa', 'ano_programa', 61, '2022', true),
    Array(31, 'programa', 'ano_programa', 62, '2025', false),
    Array(31, 'programa', 'ano_programa', 63, '2022', true),
    Array(32, 'programa', 'ano_original_programa', 56, '12345', false),
    Array(32, 'programa', 'ano_original_programa', 57, '2022', true),
    Array(33, 'programa', 'ano_original_programa', 58, 'abcd', false),
    Array(33, 'programa', 'ano_original_programa', 59, '2022', true),
    Array(34, 'programa', 'ano_original_programa', 60, '2025', false),
    Array(34, 'programa', 'ano_original_programa', 61, '2022', true),
    Array(35, 'programa', 'ano_original_programa', 62, '2025', false),
    Array(35, 'programa', 'ano_original_programa', 63, '2022', true),
    Array(36, 'programa', 'requisitos_programa', 56, 'aaaaaaa...(x300)', false),
    Array(36, 'programa', 'requisitos_programa', 57, 'Requisitos', true),
    Array(37, 'programa', 'requisitos_programa', 58, 'Test', false),
    Array(37, 'programa', 'requisitos_programa', 59, 'Requisitos', true),
    Array(38, 'programa', 'requisitos_programa', 60, 'Test@123', false),
    Array(38, 'programa', 'requisitos_programa', 61, 'Requisitos', true),
    Array(39, 'programa', 'requisitos_programa', 62, 'Test@123', false),
    Array(39, 'programa', 'requisitos_programa', 63, 'Requisitos', true),
    Array(40, 'programa', 'requisitos_programa', 64, 'Test@123', false),
    Array(40, 'programa', 'requisitos_programa', 65, 'Requisitos', true),
    Array(41, 'programa', 'poblacion_desde_programa', 66, '123', false),
    Array(41, 'programa', 'poblacion_desde_programa', 67, '10', true),
    Array(42, 'programa', 'poblacion_desde_programa', 68, ' ', false),
    Array(42, 'programa', 'poblacion_desde_programa', 69, '10', true),
    Array(43, 'programa', 'poblacion_desde_programa', 70, 'ABC', false),
    Array(43, 'programa', 'poblacion_desde_programa', 71, '10', true),
    Array(44, 'programa', 'poblacion_desde_programa', 72, 'ABC', false),
    Array(44, 'programa', 'poblacion_desde_programa', 73, '10', true),
    Array(45, 'programa', 'poblacion_hasta_programa', 74, '123', false),
    Array(45, 'programa', 'poblacion_hasta_programa', 75, '10', true),
    Array(46, 'programa', 'poblacion_hasta_programa', 76, ' ', false),
    Array(46, 'programa', 'poblacion_hasta_programa', 77, '10', true),
    Array(47, 'programa', 'poblacion_hasta_programa', 78, 'ABC', false),
    Array(47, 'programa', 'poblacion_hasta_programa', 79, '10', true),
    Array(48, 'programa', 'poblacion_hasta_programa', 80, 'ABC', false),
    Array(48, 'programa', 'poblacion_hasta_programa', 81, '10', true),
    Array(49, 'programa', 'unidad_poblacion', 82, 'DÍAS', false),
    Array(49, 'programa', 'unidad_poblacion', 83, 'MESES', true),
    Array(50, 'programa', 'unidad_poblacion', 84, 'DÍAS', false),
    Array(50, 'programa', 'unidad_poblacion', 85, 'MESES', true),
    Array(51, 'programa', 'tipo_programa', 86, 'EVALUACIÓN INTERVENCIÓN', false),
    Array(51, 'programa', 'tipo_programa', 87, 'EVALUACIÓN', true),
    Array(52, 'programa', 'tipo_programa', 88, 'EVALUACIÓN INTERVENCIÓN', false),
    Array(52, 'programa', 'tipo_programa', 89, 'EVALUACIÓN', true),
    Array(53, 'programa', 'tiempo_aplicacion_programa', 90, '12345', false),
    Array(53, 'programa', 'tiempo_aplicacion_programa', 91, '1000', true),
    Array(54, 'programa', 'tiempo_aplicacion_programa', 92, ' ', false),
    Array(54, 'programa', 'tiempo_aplicacion_programa', 93, '1000', true),
    Array(55, 'programa', 'tiempo_aplicacion_programa', 94, 'ABCD', false),
    Array(55, 'programa', 'tiempo_aplicacion_programa', 95, '1000', true),
    Array(56, 'programa', 'tiempo_aplicacion_programa', 96, 'ABCD', false),
    Array(56, 'programa', 'tiempo_aplicacion_programa', 97, '1000', true),
    Array(57, 'programa', 'descrip_interp_programa', 98, 'aaaaaaa...(x5000)', false),
    Array(57, 'programa', 'descrip_interp_programa', 99, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(58, 'programa', 'descrip_interp_programa', 100, 'Breve descripción', false),
    Array(58, 'programa', 'descrip_interp_programa', 101, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(59, 'programa', 'descrip_interp_programa', 102, '123Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', false),
    Array(59, 'programa', 'descrip_interp_programa', 103, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(60, 'programa', 'descrip_interp_programa', 104, '@Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', false),
    Array(60, 'programa', 'descrip_interp_programa', 105, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(61, 'programa', 'descrip_interp_programa', 106, 'Descripci@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', false),
    Array(61, 'programa', 'descrip_interp_programa', 107, 'Descripciónnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn', true),
    Array(62, 'programa', 'fichero_programa', 108, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(62, 'programa', 'fichero_programa', 109, 'archivo.pdf', true),
    Array(63, 'programa', 'fichero_programa', 110, 'archivo', false),
    Array(63, 'programa', 'fichero_programa', 111, 'archivo.pdf', true),
    Array(64, 'programa', 'fichero_programa', 112, 'archivo123', false),
    Array(64, 'programa', 'fichero_programa', 113, 'archivo.pdf', true),
    Array(65, 'programa', 'fichero_programa', 114, 'archivo@.txt', false),
    Array(65, 'programa', 'fichero_programa', 115, 'archivo.pdf', true),
    Array(66, 'programa', 'fichero_programa', 116, 'archivo@.txt', false),
    Array(66, 'programa', 'fichero_programa', 117, 'archivo.pdf', true),
    Array(67, 'programa', 'enlace_programa', 118, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(67, 'programa', 'enlace_programa', 119, 'http://www.ejemplo.com/archivo.html', true),
    Array(68, 'programa', 'enlace_programa', 120, 'http://.coñ', false),
    Array(68, 'programa', 'enlace_programa', 121, 'http://www.ejemplo.com/archivo.html', true),
    Array(69, 'programa', 'enlace_programa', 122, 'http://www.ejemplo123.com', false),
    Array(69, 'programa', 'enlace_programa', 123, 'http://www.ejemplo.com/archivo.html', true),
    Array(70, 'programa', 'enlace_programa', 124, 'http://www.ejemplo.com/archivo@.html', false),
    Array(70, 'programa', 'enlace_programa', 125, 'http://www.ejemplo.com/archivo.html', true),
    Array(71, 'programa', 'enlace_programa', 126, 'http://www.ejemplo.com/archivo@.html', false),
    Array(71, 'programa', 'enlace_programa', 127, 'http://www.ejemplo.com/archivo.html', true),
    Array(72, 'programa', 'formato_programa', 128, 'DIGITAL', false),
    Array(72, 'programa', 'formato_programa', 129, 'ELECTRÓNICO', true),
    Array(73, 'programa', 'formato_programa', 130, 'DIGITAL', false),
    Array(73, 'programa', 'formato_programa', 131, 'ELECTRÓNICO', true),
    Array(74, 'programa', 'modo_correccion_programa', 132, 'AUTOMÁTICO', false),
    Array(74, 'programa', 'modo_correccion_programa', 133, 'ELECTRÓNICO', true),
    Array(75, 'programa', 'modo_correccion_programa', 134, 'AUTOMÁTICO', false),
    Array(75, 'programa', 'modo_correccion_programa', 135, 'ELECTRÓNICO', true),
    Array(76, 'programa', 'modo_aplicacion_programa', 136, 'COLECTIVA', false),
    Array(76, 'programa', 'modo_aplicacion_programa', 137, 'INDIVIDUAL', true),
    Array(77, 'programa', 'modo_aplicacion_programa', 138, 'COLECTIVA', false),
    Array(77, 'programa', 'modo_aplicacion_programa', 139, 'INDIVIDUAL', true),
    Array(78, 'programa', 'imagen_programa', 140, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', false),
    Array(78, 'programa', 'imagen_programa', 141, 'imagen.jpg', true),
    Array(79, 'programa', 'imagen_programa', 142, 'imagen', false),
    Array(79, 'programa', 'imagen_programa', 143, 'imagen.jpg', true),
    Array(80, 'programa', 'imagen_programa', 144, 'imagen123', false),
    Array(80, 'programa', 'imagen_programa', 145, 'imagen.jpg', true),
    Array(81, 'programa', 'imagen_programa', 146, 'imagen@.jpg', false),
    Array(81, 'programa', 'imagen_programa', 147, 'imagen.jpg', true),
    Array(82, 'programa', 'imagen_programa', 148, 'imagen@.jpg', false),
    Array(82, 'programa', 'imagen_programa', 149, 'imagen.jpg', true),

    Array(83, 'publicacion', 'id_publicacion', 150, '123456789', false),
    Array(83, 'publicacion', 'id_publicacion', 151, '123', true),
    Array(84, 'publicacion', 'id_publicacion', 152, '', false),
    Array(84, 'publicacion', 'id_publicacion', 153, '123', true),
    Array(85, 'publicacion', 'id_publicacion', 154, 'abc123', false),
    Array(85, 'publicacion', 'id_publicacion', 155, '123', true),
    Array(86, 'publicacion', 'titulo_publicacion', 156, 'Este es un título muy largo que excede los 80 caracteres permitidos', false),
    Array(86, 'publicacion', 'titulo_publicacion', 157, 'Título válido con acentos y espacios', true),
    Array(87, 'publicacion', 'titulo_publicacion', 158, 'Corto', false),
    Array(87, 'publicacion', 'titulo_publicacion', 159, 'Título válido con acentos y espacios', true),
    Array(88, 'publicacion', 'titulo_publicacion', 160, 'Título con números 123', false),
    Array(88, 'publicacion', 'titulo_publicacion', 161, 'Título válido con acentos y espacios', true),
    Array(89, 'publicacion', 'titulo_publicacion', 162, 'Título con caracteres especiales *&^%', false),
    Array(89, 'publicacion', 'titulo_publicacion', 163, 'Título válido con acentos y espacios', true),
    Array(90, 'publicacion', 'autor_publicacion', 164, 'Autor con un nombre muy largo que excede los 40 caracteres permitidos', false),
    Array(90, 'publicacion', 'autor_publicacion', 165, 'Autor válido con acentos y espacios', true),
    Array(91, 'publicacion', 'autor_publicacion', 166, 'Corto', false),
    Array(91, 'publicacion', 'autor_publicacion', 167, 'Autor válido con acentos y espacios', true),
    Array(92, 'publicacion', 'autor_publicacion', 168, 'Autor123', false),
    Array(92, 'publicacion', 'autor_publicacion', 169, 'Autor válido con acentos y espacios', true),
    Array(93, 'publicacion', 'autor_publicacion', 170, 'Autor con caracteres especiales *&^%', false),
    Array(93, 'publicacion', 'autor_publicacion', 171, 'Autor válido con acentos y espacios', true),
    Array(94, 'publicacion', 'fecha_publicacion', 172, '31/02/2023', false),
    Array(94, 'publicacion', 'fecha_publicacion', 173, '01/12/2023', true),
    Array(95, 'publicacion', 'area_publicacion', 174, 'Área', false),
    Array(95, 'publicacion', 'area_publicacion', 175, '123', true),
    Array(96, 'publicacion', 'area_publicacion', 176, '', false),
    Array(96, 'publicacion', 'area_publicacion', 177, '123', true),
    Array(97, 'publicacion', 'area_publicacion', 178, 'abc123', false),
    Array(97, 'publicacion', 'area_publicacion', 179, '123', true),
    Array(98, 'publicacion', 'texto_publicacion', 180, 'aaaaaaa...(x8000)', false),
    Array(98, 'publicacion', 'texto_publicacion', 181, '!@#$%^&*()-_=+[{]};::::",<.>/?`~', true),
    Array(99, 'publicacion', 'texto_publicacion', 182, 'Texto corto', false),
    Array(99, 'publicacion', 'texto_publicacion', 183, '!@#$%^&*()-_=+[{]};::::",<.>/?`~', true),
    Array(100, 'publicacion', 'imagen_publicacion', 184, 'imagen.jpg', false),
    Array(100, 'publicacion', 'imagen_publicacion', 185, 'ImagenValida.jpg', true),
    Array(101, 'publicacion', 'imagen_publicacion', 186, 'corta.jpg', false),
    Array(101, 'publicacion', 'imagen_publicacion', 187, 'ImagenValida.jpg', true),
    Array(102, 'publicacion', 'imagen_publicacion', 188, 'Imagen con acentos y espacios.jpg', false),
    Array(102, 'publicacion', 'imagen_publicacion', 189, 'ImagenValida.jpg', true),
    Array(103, 'publicacion', 'imagen_publicacion', 190, 'imagen.png', false),
    Array(103, 'publicacion', 'imagen_publicacion', 191, 'ImagenValida.jpg', true)
    
);
